syncfusion-content/ej2-vue-docs

ej2-vue-toc.html
**Description**
Removed Unwanted Double quote
=> ES-826500: Removed unwanted Double Quote

ej2-vue-toc.html, ej2-vue/code-snippet/appbar/getting-started-cs10/index.css, ej2-vue/gantt/getting-started.md
=> documentation(841427): Resolved conflict issues

ej2-vue/code-snippet/image-editor/getting-started-cs1/index.js
847785 - Image change committed
=> 847785 - Image change committed

ej2-vue/document-editor/table.md
Hi @MallikaRK ,
Worked on page with redirect for Vue control.
Regards,
Sharly A.
=> SEO-175665 - Vue controls changes

ej2-vue/document-editor/getting-started.md, ej2-vue/pdfviewer/how-to/extract-text.md, ej2-vue/spreadsheet/getting-started.md
HI @MallikaRK ,
Please review the changes.
Thanks.
Regards,
Edith.
=> SEO-176496-Vue-ej2-page-with-redirect-links

ej2-vue/datetimepicker/how-to/disable-the-datetimepicker-component.md, ej2-vue/drop-down-list/getting-started.md, ej2-vue/gantt/appearance-customization.md, ej2-vue/tab/getting-started.md, ej2-vue/tooltip/getting-started.md
Hi @MallikaRK ,
Worked on page with redirect for Vue controls.
Regards,
Sharly A.
=> SEO-177266 - Vue Controls changes

ej2-vue/auto-complete/data-binding.md, ej2-vue/calendar/accessibility.md, ej2-vue/circular-gauge/getting-started.md, ej2-vue/dashboard-layout/interaction-with-panels/dragging-moving-of-panels.md, ej2-vue/gantt/columns/columns.md, ej2-vue/pivotview/conditional-formatting.md, ej2-vue/radio-button/getting-started.md, ej2-vue/rich-text-editor/markdown.md, ej2-vue/rich-text-editor/video.md
Hi @MallikaRK,
Worked on page with redirect issue fixed.
Regards,
Sharly A.
=> SEO-1772266 - Vue page with redirect changes

ej2-vue/grid/editing/edit.md, ej2-vue/radio-button/getting-started.md, ej2-vue/sidebar/getting-started.md, ej2-vue/spreadsheet/getting-started.md, ej2-vue/tab/drag-and-drop.md, ej2-vue/textbox/getting-started.md, ej2-vue/timepicker/getting-started.md, ej2-vue/treegrid/columns/columns.md
Hi @MallikaRK,
Worked on page with redirect issue fixed.
Regards,
Sharly A.
=> SEO-177266 - Vue page with redirect changes

ej2-vue/breadcrumb/getting-started.md, ej2-vue/smithchart/getting-started.md, ej2-vue/uploader/form-support.md
Hi @MallikaRK,
Worked on page with redirect.
Regards,
Sharly A.
=> SEO-177725 - Vue page with redirect changes

ej2-vue/calendar/vue3-getting-started.md, ej2-vue/chart/chart-type/line.md, ej2-vue/check-box/getting-started.md, ej2-vue/document-editor/getting-started.md, ej2-vue/document-editor/table.md, ej2-vue/drop-down-list/filtering.md, ej2-vue/tab/getting-started.md, ej2-vue/uploader/getting-started.md
Hi @Aishwarya-Ganesan,
Have worked on Page with Redirect links.
Regards,
Yvone.
=> SEO-177250 Vue Page with Redirect

ej2-vue/circular-gauge/getting-started.md, ej2-vue/diagram/getting-started.md, ej2-vue/document-editor/how-to/customize-font-family-drop-down.md, ej2-vue/list-box/getting-started.md, ej2-vue/schedule/recurrence-editor.md, ej2-vue/tab/getting-started.md
Hi @Aishwarya-Ganesan,
Have worked on Page with Redirect links.
Regards,
Yvone.
=> SEO-177251 Vue Page with Redirect

ej2-vue/accumulation-chart/getting-started.md, ej2-vue/calendar/accessibility.md, ej2-vue/datepicker/accessibility.md, ej2-vue/diagram/getting-started.md, ej2-vue/document-editor/getting-started.md, ej2-vue/maps/getting-started.md, ej2-vue/schedule/recurrence-editor.md
Hi @MallikaRK ,
Please review the ej2 UG redirect link changes.
Thanks.
Regards,
Edith.
=> SEO-177303-Vue-ej2-page-with-redirect-links

ej2-vue/accordion/getting-started.md, ej2-vue/calendar/how-to/set-clear-button-in-calendar.md, ej2-vue/card/card-image.md, ej2-vue/diagram/connectors.md, ej2-vue/diagram/interaction.md, ej2-vue/drop-down-button/getting-started.md, ej2-vue/drop-down-list/templates.md, ej2-vue/schedule/appointments.md, ej2-vue/toolbar/item-configuration.md, ej2-vue/treegrid/filtering/filtering.md, ej2-vue/treeview/template.md, ej2-vue/uploader/getting-started.md
Hi @MallikaRK,
Please find and review the changes made.
Regards,
Scholar.
=> SEO-176927-Vue-Page-With-Redirect-Links

ej2-vue/daterangepicker/getting-started.md
Hi @gowthamanthavasiyappan ,
Kindly review the below dropped keywords changes for Vue DateRangePicker.
Regards,
Sharly A.
=> SEO-177658 - Vue DateRangePicker Int

ej2-vue/schedule/getting-started.md
Hello,
Worked on missing alt text.
Regards,
Beryl.
=> SEO-176893-Missing-Alt-Text-Vue

ej2-vue/splitter/getting-started.md, ej2-vue/tab/getting-started.md, ej2-vue/tab/orientation.md
Hi @Aishwarya-Ganesan,
Have worked on Page with Redirect links.
Regards,
Yvone.
=> SEO-1777251 Vue Page with Redirect

ej2-vue/card/getting-started.md, ej2-vue/image-editor/transform.md, ej2-vue/sidebar/getting-started.md
Hi @MallikaRK ,
Have made changes to the redirect links,
Please review.
Thanks.
Regards,
Edith.
=> SEO-176838-vue-ej2-page-with-redirect

ej2-vue/timeline/getting-started.md
Need to remove the wrong getting started link map to timeline.
=> UG(877772): Remove wrong getting started link map to timeline.

ej2-vue-toc.html, ej2-vue/code-snippet/grid/group/component-group-caption/index.js, ej2-vue/code-snippet/image-editor/getting-started-cs34/index.js, ej2-vue/grid/grouping/grouping.md, ej2-vue/grid/pdf-export/pdf-export.md
=> Resolved the conflict issues

ej2-vue/context-menu/how-to/template.md
858328: Context menu issue resolved
=> 858328: Context menu issue resolved

ej2-vue/circular-chart-3d/tooltip.md
Need to Resolve the Issue in Md files
Add the proper quotes in md files
NA
NA
Feature matrix document updated against this feature and committed in this [common location](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX …
=> 901737: Resolved the Issues in Md files

ej2-vue-toc.html, ej2-vue/code-snippet/chart/series/addpoint-cs/index.html, ej2-vue/code-snippet/chart/series/addpoint-cs3/index.html, ej2-vue/code-snippet/chart/series/pie-cs39/index.html, ej2-vue/code-snippet/datetimepicker/getting-started-cs11/index.html, ej2-vue/code-snippet/grid/page/default-page1/systemjs.config.js, ej2-vue/code-snippet/grid/page/default-page5/systemjs.config.js
Need to resolve the conflict files
Need to resolve the conflict files
NA
NA
Feature matrix document updated against this feature and committed in this [common location](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes …
=> 910309: Need to resolve the conflict files 

ej2-vue/ai-assistview/getting-started.md, ej2-vue/ai-assistview/vue3-getting-started.md, ej2-vue/code-snippet/ai-assistview/defaultprompts/app-composition.vue, ej2-vue/code-snippet/ai-assistview/defaultprompts/app.vue, ej2-vue/code-snippet/ai-assistview/getting-started/app-composition.vue, ej2-vue/code-snippet/ai-assistview/getting-started/app.vue
Need to update getting started contents and samples in Vue for AI AssistView component.
NA
None
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? NA.
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? No
* Did you record this case in the unit test or UI test? No
=> docs(911015): need to update getting started contents and samples for AI AssistView

ej2-vue/appearance/css-variables.md
Need to Resolve conflict files
Need to Resolve conflict files
NA
NA
Feature matrix document updated against this feature and committed in this [common location](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
Provide the test bed …
=> 919816: Need to Resolve conflict files

ej2-vue/pdfviewer/print.md
Description:
Resolved conflict in print.md file in Vue docs
=> 1234: resolved conflict

ej2-vue/uploader/chunk-upload.md
=> 12345: Resolving conflict

ej2-vue-toc.html, ej2-vue/code-snippet/chart/accessibility/title/index.js, ej2-vue/list-box/drag-and-drop.md
Need to Resolve conflict files
Need to Resolve conflict files
NA
NA
Feature matrix document updated against this feature and committed in this [common location]([https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents)](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents)&xsdata=MDV8MDJ8fDYxYWU4YmIxYWVlOTQxZjRjZTUxMDhkZDQwMzMzYWE5fDc3ZjFmZTEyYjA0OTQ5MTk4YzUwOWZiNDFlNWJiNjNifDB8MHw2Mzg3MzczMTA5MjgxOTUxNTN8VW5rbm …
=> 936558: resolved the conflict for Vue docs

ej2-vue/tooltip/getting-started.md
Hi @Gowthaman
|Title|Description|
|--|--|
|Task Category|Coverage-vue-docs|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/ej2-vue-docs/pull/584 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198307/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc.aspx?sourcedoc=%7Bd34a712d-4b55-4333-a940-c23ca3501b9c%7D&action=edit&isSPOFile=1&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Chillaryochiengo%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNTAzMDIwMTAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection …
=> SEO-198307-coverage-vue-docs

ej2-vue/numerictextbox/getting-started.md
Hi @Gowthaman
|Title|Description|
|--|--|
|Task Category|Coverage-vue-docs|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/ej2-vue-docs/pull/585 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198307/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc.aspx?sourcedoc=%7Bd34a712d-4b55-4333-a940-c23ca3501b9c%7D&action=edit&isSPOFile=1&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Chillaryochiengo%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNTAzMDIwMTAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection …
=> SEO-198307-Coverage-work-Vue-docs1

ej2-vue/sidebar/getting-started.md
Hi @Gowthaman
|Title|Description|
|--|--|
|Task Category|Coverage-vue-docs|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/ej2-vue-docs/pull/586 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198307/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc.aspx?sourcedoc=%7Bd34a712d-4b55-4333-a940-c23ca3501b9c%7D&action=edit&isSPOFile=1&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Chillaryochiengo%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNTAzMDIwMTAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection …
=> SEO-198307-coverage-vue-docs2

ej2-vue-toc.html, ej2-vue/block-editor/appearance.md, ej2-vue/block-editor/blocks.md, ej2-vue/block-editor/drag-drop.md, ej2-vue/block-editor/editor-menus.md, ej2-vue/block-editor/events.md, ej2-vue/block-editor/getting-started.md, ej2-vue/block-editor/globalization.md, ej2-vue/block-editor/keyboard-shortcuts.md, ej2-vue/block-editor/methods.md, ej2-vue/block-editor/paste-cleanup.md, ej2-vue/block-editor/undo-redo.md
Need to port the content for the Block editor component in the main repo
NA
NA
NA
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated.
NA
UX changes got approval if UI is added or modified?
Drafted UG for this feature?
Content team reviewed the UI content changes.
Is this the common feature which needs to be addressed in the same component or on other components in our platform?
Is there any existing behavior change due to this code change?
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes cause any memory leak and performance issue?
Created task in Blazor to synchronize if the …
=> 965810: Added a block editor UG in main repo
